// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeAbGnTr1rKdQ5XhTVwcxpeZlrlIrAw9Y',
    appId: '1:742700902793:web:66c107d7520f15a526d958',
    messagingSenderId: '742700902793',
    projectId: 'fir-tutorial-be3d8',
    authDomain: 'fir-tutorial-be3d8.firebaseapp.com',
    storageBucket: 'fir-tutorial-be3d8.appspot.com',
    measurementId: 'G-8NHGZWXJCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEsdPBOoiaY7Pr6-d2LHvyb30N3XzqH88',
    appId: '1:742700902793:android:00443019e841a93c26d958',
    messagingSenderId: '742700902793',
    projectId: 'fir-tutorial-be3d8',
    storageBucket: 'fir-tutorial-be3d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApwAeTL3KWyhNOU6SM2Li1KeLbojNcG-w',
    appId: '1:742700902793:ios:e9f940cec7f60a1226d958',
    messagingSenderId: '742700902793',
    projectId: 'fir-tutorial-be3d8',
    storageBucket: 'fir-tutorial-be3d8.appspot.com',
    androidClientId:
        '742700902793-pal67qa4iegdseelj0dqhet2rghp1g6l.apps.googleusercontent.com',
    iosClientId:
        '742700902793-pf20n2obdu2i9lao884lu9ku1v4pkkeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApwAeTL3KWyhNOU6SM2Li1KeLbojNcG-w',
    appId: '1:742700902793:ios:e9f940cec7f60a1226d958',
    messagingSenderId: '742700902793',
    projectId: 'fir-tutorial-be3d8',
    storageBucket: 'fir-tutorial-be3d8.appspot.com',
    androidClientId:
        '742700902793-pal67qa4iegdseelj0dqhet2rghp1g6l.apps.googleusercontent.com',
    iosClientId:
        '742700902793-pf20n2obdu2i9lao884lu9ku1v4pkkeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeAbGnTr1rKdQ5XhTVwcxpeZlrlIrAw9Y',
    appId: '1:742700902793:web:877a00e946741a9b26d958',
    messagingSenderId: '742700902793',
    projectId: 'fir-tutorial-be3d8',
    authDomain: 'fir-tutorial-be3d8.firebaseapp.com',
    storageBucket: 'fir-tutorial-be3d8.appspot.com',
    measurementId: 'G-M59YZHVX2G',
  );
}
